CREATE TABLE sous_groupe(
   alim_grp_code     INTEGER  NOT NULL PRIMARY KEY 
  ,alim_grp_nom_fr   VARCHAR(43) NOT NULL
);
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (101,'salades composées et crudités');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (102,'soupes');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (103,'plats composés');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (104,'pizzas, tartes et crêpes salées');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (105,'sandwichs');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (106,'feuilletées et autres entrées');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (201,'légumes');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (202,'pommes de terre et autres tubercules');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (203,'légumineuses');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (204,'fruits');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (205,'fruits à coque et graines oléagineuses');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (301,'pâtes, riz et céréales');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (302,'pains et viennoiseries');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (303,'céréales de petit-déjeuner et biscuits');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (304,'gâteaux et pâtisseries');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (305,'farines et pâtes à tarte');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (401,'viandes cuites');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (402,'viandes crues');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (403,'charcuteries');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (404,'autres produits à base de viande');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (405,'poissons cuits');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (406,'poissons crus');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (407,'mollusques et crustacés cuits');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (408,'mollusques et crustacés crus');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (409,'produits à base de poissons et produits de la mer');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (410,'œufs');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (501,'laits');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (502,'produits laitiers frais et assimilés');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (503,'fromages');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (504,'crèmes et spécialités à base de crème');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (601,'eaux');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (602,'boissons sans alcool');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (603,'boisson alcoolisées');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (701,'sucres, miels et assimilés');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (702,'chocolats et produits à base de chocolat');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (703,'confiseries non chocolatées');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (704,'confitures et assimilés');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (801,'glaces');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (802,'sorbets');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (803,'desserts glacés');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (901,'beurres');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (902,'huiles et graisses végétales');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (903,'margarines');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (904,'huiles de poissons');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (905,'autres matières grasses');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1001,'sauces');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1002,'condiments');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1003,'aides culinaires');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1005,'épices');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1006,'herbes');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1007,'algues');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1008,'denrées destinées à une alimentation particulière');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1009,'ingrédients divers');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1101,'laits et boissons infantiles');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1102,'petits pots salés et plats infantiles');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1103,'desserts infantiles');
INSERT INTO sous_groupe(alim_grp_code,alim_grp_nom_fr) VALUES (1104,'céréales et biscuits infantiles');
