CREATE TABLE sous_sous_groupe(
   alim_ssssgrp_code   INTEGER  NOT NULL PRIMARY KEY
  ,alim_ssssgrp_nom_fr VARCHAR(44)
);
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (0,NULL);
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10301,'plats de viande sans garniture');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10302,'plats de viande et féculents');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10303,'plats de viande et légumes/légumineuses');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10304,'plats de poisson sans garniture');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10305,'plats de poisson et féculents');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10306,'plats de légumes/légumineuses');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10307,'plats de céréales/pâtes');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (10308,'plats de fromage');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20101,'légumes crus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20102,'légumes cuits');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20103,'légumes séchés ou déshydratés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20301,'légumineuses cuites');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20302,'légumineuses fraîches');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20303,'légumineuses sèches');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20401,'fruits crus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20402,'compotes et assimilés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20403,'fruits appertisés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (20404,'fruits séchés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30101,'pâtes, riz et céréales cuits');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30102,'pâtes, riz et céréales crus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30201,'pains');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30202,'biscottes et pains grillés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30203,'viennoiseries');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30301,'céréales de petitdéjeuner');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30302,'barres céréalières');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30303,'biscuits sucrés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30304,'biscuits apéritifs');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30501,'farines');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (30502,'pâtes à tarte');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40101,'bœuf et veau');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40102,'porc');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40103,'poulet');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40104,'dinde');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40105,'agneau et mouton');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40106,'gibier');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40107,'autres viandes');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40108,'abats');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40201,'bœuf et veau');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40202,'porc');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40203,'poulet');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40204,'dinde');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40205,'agneau et mouton');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40206,'gibier');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40207,'autres viandes');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40208,'abats');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40301,'jambons cuits');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40302,'jambons secs et crus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40303,'saucisson secs');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40304,'saucisses et assimilés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40305,'pâtés et terrines');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40306,'rillettes');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40307,'quenelles');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (40308,'autres spécialités charcutières');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (41001,'œufs cuits');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (41002,'œufs crus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (41003,'omelettes et autres ovoproduits');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50101,'laits de vaches liquides (non concentrés)');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50102,'laits autres que de vache');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50103,'laits de vache concentrés ou en poudre');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50201,'yaourts et spécialités laitières type yaourt');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50202,'fromages blancs');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50203,'desserts lactés');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50204,'autres desserts');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50301,'fromages à pâte molle');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50302,'fromages à pâte persillée');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50303,'fromages à pâte pressée');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50304,'fromage fondus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (50305,'autres fromages et spécialités');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60201,'jus');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60202,'nectars');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60203,'boissons rafraîchissantes sans alcool');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60204,'boissons rafraîchissantes lactées');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60205,'boissons végétales');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60206,'café, thé, cacao etc. prêts à consommer');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60207,'boissons à reconstituer');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60301,'vins');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60302,'bières et cidres');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (60304,'cocktails');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (100101,'sauces condimentaires');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (100102,'sauces chaudes');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (100103,'sauces sucrées');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (100601,'herbes fraîches');
INSERT INTO sous_sous_groupe(alim_ssssgrp_code,alim_ssssgrp_nom_fr) VALUES (100602,'herbes séchées');
